export let userLibraries: any = {owned: "Lo tengo", wishlist: "Lista de deseados"};

export let gameRegions: string[] = ["PAL", "NTSC-J", "NTSC-U", "NTSC-A"];

export let currencies: any = {
  yen: {name: 'Yen Japonés', symbol: '¥'},
  euro: {name: 'Euro', symbol: '€'},
  dolar: {name: 'Dolar Americano', symbol: '$'},
  pound: {name: 'Libra Esterlina', symbol: '£'},
};

export let platforms: string[] = [
  "Dreamcast",
  "GameBoy",
  "GameBoy Advance",
  "GameBoy COlor",
  "Master System",
  "Mega Drive",
  "Microsoft Windows",
  "NES",
  "New Nintendo 3DS",
  "Nintendo 3DS",
  "Nintendo 64",
  "Nintendo DS",
  "Nintendo DSi",
  "Nintendo Gamecube",
  "Nintendo Switch",
  "Nintendo Wii",
  "Nintendo WiiU",
  "Nintendo WiiWare",
  "Origin",
  "Playstation",
  "Playstation 2",
  "Playstation 3",
  "Playstation 4",
  "Playstation Portable",
  "Playstation Vita",
  "Sega Saturn",
  "SNES",
  "Steam",
  "Xbox",
  "Xbox 360",
  "Xbox One"
];

export let genres: string[] = [
  "Acción",
  "Arcade",
  "Action RPG",
  "Aventuras",
  "Aventura conversacional",
  "Aventura gráfica",
  "Battle Royale",
  "Beat 'em up",
  "Carreras",
  "Deporte",
  "Estrategia en tiempo real",
  "Estrategia por turnos",
  "First person shooter",
  "Hack and slash",
  "Horror",
  "JRPG",
  "Lucha",
  "Puzzle",
  "Metroidvania",
  "Miedo",
  "Minijuegos",
  "MMORPG",
  "Musical",
  "Plataformas",
  "Ritmo",
  "Roguelikes",
  "RPG",
  "RPG Táctico",
  "Shoot 'em up",
  "Soulslike",
  "Sigilo",
  "Simulación de citas",
  "Simulación de conducción",
  "Simulación de construcción",
  "Simulación de vida",
  "Simulación de vuelo",
  "Supervivencia",
  "Survival horror",
  "Novela visual"
];
